

/* PROCEDURES COM REGRA DE NEGOCIO */

@@IDENTITY - GUARDA O ULTIMO IDENTITY INSERIDO NA SEÇÃO

-- MONTANDO REGRA PRA INSERIR EM 2 TABELAS

-- PROC DE CADASTRO
CREATE PROC CADASTRO @NOME VARCHAR(30), @SEXO CHAR(1), @NASCIMENTO DATE,
@TIPO CHAR(3), @NUMERO VARCHAR(10)
AS
	DECLARE @FK INT 
	
	INSERT INTO PESSOA VALUES(@NOME, @SEXO, @NASCIMENTO) -- GERA O ID
	
	SET @FK = (SELECT IDPESSOA FROM PESSOA WHERE ID PESSOA = @@IDENTITY)
	
	INSERT INTO TELEFONE VALUES(@TIPO,@NUMERO,@FK)
GO

EXEC CADASTRO 'JORGE', 'M', '1981-01-01', 'CEL', '99904578'
GO
