

/* FUNCOES DE DATAS */

-- ANO/MES/DIA
-- YYY/MM/DD

/* QUERY COM DAY, MONTH, YEAR */

SELECT NOME,
DAY(NASCIMENTO)
FROM ALUNO
GO

SELECT NOME,
MONTH(NASCIMENTO)
FROM ALUNO
GO

SELECT NOME,
YEAR(NASCIMENTO)
FROM ALUNO
GO

/* DATEDIFF - CALCULA DIFERENÇA ENTRE DUAS DATAS */
-- DATEDIFF( INTERVALO , DATA_INICIO  , DATA_FINAL ,)

-- FUNÇAO GETDATE() - TRAZ DIA E HORA
SELECT NOME, GETDATE() AS DIA_HORA
FROM ALUNOS
GO

-- DATEDIFF( INTERVALO , DATA_INICIO  , DATA_FINAL ,) - RETORNA INTEIRO
SELECT NOME, DATEDIFF(DAY,NASCIMENTO,GETDATE()) AS DIFERENÇA_ENTRE_DATAS
FROM TABELA
GO

-- RETORNO EM INTEIRO + OPERAÇAO MATEMATICA
-- (DATEDIFF(DAY,NASCIMENTO,GETDATE())/365) - RETORNA OS ANOS
SELECT NOME, (DATEDIFF(DAY,NASCIMENTO,GETDATE())/365) AS DIFERENÇA_ENTRE_DATAS
FROM TABELA
GO

-- (DATEDIFF(MONTH,NASCIMENTO,GETDATE())/12) - RETORNA OS MESES
SELECT NOME, (DATEDIFF(MONTH,NASCIMENTO,GETDATE())/12) AS DIFERENÇA_ENTRE_DATAS
FROM TABELA
GO

-- (DATEDIFF(YEAR,NASCIMENTO,GETDATE())  - RETORNA OS ANOS
SELECT NOME, DATEDIFF(YEAR,NASCIMENTO,GETDATE()) AS DIFERENÇA_ENTRE_DATAS
FROM TABELA
GO

/* DATENAME - TRAZ O NOME DA PARTE DA DATA EM QUESTAO */
-- TRAZ O NOME DO MES, ANO, DIA
-- DATENAME(ACAO, COLUNA_QUE_TENHA_DATA)  - RETORNA STRING

-- RETORNA O NOME DO MES
SELECT NOME, DATENAME(MONTH, NASCIMENTO)
FROM ALUNO
GO

-- RETORNA O NOME DO DIA
SELECT NOME, DATENAME(WEEKDAY, NASCIMENTO)
FROM ALUNO
GO

-- RETORNA O NOME DO ANO
SELECT NOME, DATENAME(YEAR, NASCIMENTO)
FROM ALUNO
GO

/* DATEPART - TRAZ O NOME DA PARTE DA DATA EM QUESTAO, POREM RETORNA INTEIRO */
-- TRAZ O NOME DO MES, ANO, DIA
-- DATEPART(ACAO, COLUNA_QUE_TENHA_DATA)  - RETORNA INTEIRO

-- RETORNA O NOME DO MES
SELECT NOME, DATEPART(MONTH, NASCIMENTO)
FROM ALUNO
GO

-- RETORNA O NOME DO ANO
SELECT NOME, DATEPART(YEAR, NASCIMENTO)
FROM ALUNO
GO

-- RETORNA O NOME DO DIA
SELECT NOME, DATEPART(WEEKDAY, NASCIMENTO)
FROM ALUNO
GO

/* DATEADD - RETORNA UMA DATA SOMANDO A OUTRA DATA */
-- DATEADD(INTERVALO, INCREMENTO INT, EXPRESSAO DATE) - RETORNA DATA

-- SOMA 365 DIAS COM A DATA DE HOJE
SELECT DATEADD(DAY, 365, GETDATE())

-- SOMA 10 ANOS COM A DATA DE HOJE
SELECT DATEADD(YEAR, 10, GETDATE())

-- SOMA 5 MESES COM A DATA DE HOJE
SELECT DATEADD(MONTH, 5, GETDATE())

/* MESCLANDO FUNÇÕES DE DATAS */

SELECT NOME, DATEPART(WEEKDAY, NASCIMENTO), DATENAME(YEAR, NASCIMENTO)
FROM ALUNO
GO













