

/* VIEWS */

-- CRIA ALGO PARA CHAMAR AS QUERY 

-- CREATE VIEW NomeView AS QUERY, CRIA VIEW
-- UM BOM METODO  É CRIAR COM UM PREFIXO DE VIEW, View_NomeView

-- SELECT * FROM NomeView, CHAMA VIEW

-- SLECT NOME, NUMERO, ESTADO FROM View_NomeView, CHAMANDO COM ALGUNS DADOS

-- SHOW TABLES, MOSTRA AS VIEWS JUNTAMENTE COM AS TABELAS

-- DROP VIEW NomeView, APAGA AS VIEWS

-- CRIANDO
CREATE VIEW View_Invoca AS
SELECT C.NOME, 
	C.SEXO, 
	C.EMAIL, 
	N.NUMERO, 
	E.BAIRRO, 
	E.CIDADE, 
	E.ESTADO
FROM CLIENTE C
INNER JOIN ENDERECO E
ON C.IDCLIENT = E.IDCLIENT
INNER JOIN NUMERO N
ON C.IDCLIENT = N.IDCLIENT

-- CHAMANDO
SELECT * FROM View_Invoca

-- CHAMANDO COM ALGUNS DADOS
SELECT NOME, NUMERO, ESTADO FROM View_Invoca

-- MOSTRANDO 
SHOW TABLES;

-- APAGANDO
DROP VIEW View_Invoca
