

/* TRIGGERS DE RANGE - INTRODUÇÃO A TRANSAÇÕES */

-- TESTE
CREATE TABLE SALARIO_RANGE(
	MINSAL MONEY,
	MAXSAL MONEY
);
GO

INSERT INTO SALARIO_RANGE VALUES(3000.00, 6000.00)
GO

-- TRIGGER
CREATE TRIGGER TRG_RANGE
ON DBO.EMPREGADO -- OUTRA PAGINA
FOR INSERT, UPDATE
AS
	DECLARE
		@MINSAL MONEY,
		@MAXSAL MONEY,
		@ATUALSAL MONEY
				
	SELECT @MINSAL = MINSAL, @MAXSAL = MAXSAL
	FROM SALARIO_RANGE
	
	SELECT @ATUALSAL = I.SALARIO
	FROM INSERTED I
	
	-- VALIDANDO O SALARIO
	IF(@ATUALSAL < @MINSAL)
	BEGIN
		-- MENSAGEM DE ERRO
		RAISERROR('SALARIO MENOR QUE O PISO', 16, 1)
		ROLLBACK TRANSACTION -- VOLTE A TRANSAÇÃO
	END
	
	IF(@ATUALSAL > MAXSAL)
	BEGIN
		RAISERROR('SALARIO MAIOR QUE O TETO', 16, 1)
		ROLLBACK TRANSACTION -- VOLTE A TRANSAÇÃO
	END	
GO

/* VERIFICANDO A TRIIGER EM TEXTO */
SP_HELPTEXT NOME_TRIGGER
GO






