

/* TRIGEGR DE DML */


/* ESTRUTURA */
CREATE TRIGGER TRG_NOMETRIGGER
ON DBO.TABELA
FOR OPERACAO -- QUANDO, INSERT, DELETE,UPDATE
AS
/* CASO HOUVER VALIDAÇÃO NA TRIGGER
	IF OPERACAO(TABELA)    IF UODATE(PRECO) 
	BEGIN				   BEGIN
	END					   END
*/
	VARIAVEIS
	/*
	EX. DECLARE @VARIAVEL INT
	*/
	
	ACRESCENTANDO VALOR NA VARIAVEL
	-- QUANDO O VALOR DA VARIAVEL ESTA NA TABELA, QUANDO É UM COLUNA
	-- USA INSERTED - INSERIR OU DELETED - DELETAR
	/*
		SELECT @PRECO = PRECO FROM DELETED
		SELECT @PRECONOVO = PRECO FROM INSERTED
	*/
	
	SETANDO AS VARIAVEIS QUE NAO TEM VALOR NA TABELAA
	/*
		SET @DATA = GETDATE()
		SET @USUARIO = SUSER_NAME()
		SET @MENSAGEM = " VALOR INSERIDO PELA TRIGGER TRG_ATUALIZA_PRECO"
	*/
	
	INSERINDO AS VARIAVEIS NA TABELA
	/*
		INSERT INTO HISTORICO(PRODUTO,CATEGORIA,PRECOANTIGO,PRECONOVO,DATA,USUARIO,MENSAGEM)
		VALUES (@PRODUTOM,@CATEGORIA,@PRECO,@PRECONOVO,@DATA,@USUARIO,@MENSAGEM)
	*/
	
	IMPRIMI ALGO NA TELA
	/*
		PRINT "TRIGGER EXECUTADA COM SUCESSO"
	*/

GO

	
/* CRIANDO TABELA DE TESTE, INSERT */
CREATE TABLE PRODUTOS(
	IDPRODUTO INT PRIMARY KEY IDENTITY,
	NOME VARCHAR(50) NOT NULL,
	CATEGORIA VARCHAR(30) NOT NULL,
	PRECO NUMERIC(10,2) NOT NULL
)
GO

CREATE TABLE HISTORICO(
	IDOPERACAO INT PRIMARY KEY IDENTITY,
	PRODUTO VARCHAR(50) NOT NULL,
	CATEGORIA VARCHAR(30) NOT NULL,
	PRECOANTIGO NUMERIC(10,2) NOT NULL,
	PRECONOVO NUMERIC(10,2) NOT NULL
	DATA DATETIME,
	USUARIO VARCHAR(30),
	MENSAGEM VARCHAR(100)
)
GO

-- INSERINDO NA TABELA PRODUTOS
INSERT INTO PRODUTOS VALUES('CAMISA', 'ROUPAA', 50.00 );
INSERT INTO PRODUTOS VALUES('TINTURA', 'SAPATOS', 53.00 );
INSERT INTO PRODUTOS VALUES('CAMISA', 'PROMOCOES', 70.00 );
INSERT INTO PRODUTOS VALUES('LIVRO SQL', 'LIVROS', 500.00 );
INSERT INTO PRODUTOS VALUES('SANDALIA', 'SAPATO', 880.00 );
GO

/* VERIRIFCANDO O USUARIO DO BANCO */
SELECT SUSER_NAME();
GO

/* CRIANDO TRIGGERS DE DADOS - DML */
CREATE TRIGGER TRG_ATUALIZA_PRECO
ON DBO.PRODUTOS
FOR UPDATE AS
IF UPDATE(PRECO)
BEGIN

	DECLARE @IDPRODUTO INT
	DECLARE @PRODUTO VARCHAR(30)
	DECLARE @CATEGORIA VARCHAR(10)
	DECLARE @PRECO NUMERIC(10,2)
	DECLARE @PRECONOVO NUMERIC(10,2)
	DECLARE @DATA DATETIME
	DECLARE @USUARIO VARCHAR(30)
	DECLARE @MENSAGEM VARCAHR(1000)
	
	-- ACRESCENTANDO VALOR NA VARIAVEL
	SELECT @IDPRODUTO = IDPRODUTO FROM INSERTED
	SELECT @PRODUTO = NOME FROM INSERTED
	SELECT @CATEGORIA = CATEGORIA FROM INSERTED
	SELECT @PRECO = PRECO FROM DELETED
	SELECT @PRECONOVO = PRECO FROM INSERTED
	
	-- SETANDO AS VARIAVEIS QUE NAO ESTAO NA TABELA
	SET @DATA = GETDATE()
	SET @USUARIO = SUSER_NAME()
	SET @MENSAGEM = " VALOR INSERIDO PELA TRIGGER TRG_ATUALIZA_PRECO"
	
	-- INSERINDO AS VARIAVEIS NA TABELA
	INSERT INTO HISTORICO(PRODUTO,CATEGORIA,PRECOANTIGO,PRECONOVO,DATA,USUARIO,MENSAGEM)
	VALUES (@PRODUTOM,@CATEGORIA,@PRECO,@PRECONOVO,@DATA,@USUARIO,@MENSAGEM)
	
	-- IMPRIMI ALGO NA TELA
	PRINT "TRIGGER EXECUTADA COM SUCESSO"
END
GO
	
	

























