

/* TRIGEGR USANDO SELECT */


/* ESTRUTURA */
CREATE TRIGGER TRG_NOMETRIGGER
ON DBO.TABELA
FOR OPERACAO -- QUANDO, INSERT, DELETE,UPDATE
AS
/* CASO HOUVER VALIDAÇÃO NA TRIGGER
	IF OPERACAO(TABELA)    IF UODATE(PRECO) 
	BEGIN				   BEGIN
	END					   END
*/
	VARIAVEIS
	/*
	EX. DECLARE @VARIAVEL INT
	*/
	
	ACRESCENTANDO VALOR NA VARIAVEL
	-- QUANDO O VALOR DA VARIAVEL ESTA NA TABELA, QUANDO É UM COLUNA
	-- USA INSERTED - INSERIR OU DELETED - DELETAR
	/*
		SELECT @PRECO = PRECO FROM DELETED
		SELECT @PRECONOVO = PRECO FROM INSERTED
	*/
	
	SETANDO AS VARIAVEIS QUE NAO TEM VALOR NA TABELAA
	/*
		SET @DATA = GETDATE()
		SET @USUARIO = SUSER_NAME()
		SET @MENSAGEM = " VALOR INSERIDO PELA TRIGGER TRG_ATUALIZA_PRECO"
	*/
	
	INSERINDO AS VARIAVEIS NA TABELA
	/*
		INSERT INTO HISTORICO(PRODUTO,CATEGORIA,PRECOANTIGO,PRECONOVO,DATA,USUARIO,MENSAGEM)
		VALUES (@PRODUTOM,@CATEGORIA,@PRECO,@PRECONOVO,@DATA,@USUARIO,@MENSAGEM)
	*/
	
	IMPRIMI ALGO NA TELA
	/*
		PRINT "TRIGGER EXECUTADA COM SUCESSO"
	*/

GO