
-- CHAVE - CONSTRAINT - (REGRA)

/* VERIFICAR A CHAVE */
SHOW CREATE TABLE Tabela

/* ORGANIZAÇÃO DE CHAVES */

-- A BOA PRATICA É CRIAR A TABELA PRIMEIRO
-- E DEPOIS CRIAS AS CHAVES POR FORA DAS TABELAS
-- POR CAUSA DO NOME NO DICIONARIO DO BANCO

/* ORGANIZAÇÃO DE CHAVES E ACOES DE CONSTRAINT*/

CREATE TABLE CLIENTE(
	IDCLIENTE INT,
	NOME VARCHAR(30) NOT NULL
);

CREATE TABLE TELEFONE(
	IDTELEFONE INT,
	TIPO CHAR(2),
	NUMERO VARCHAR(30),
	IDCLIENTE INT -- ADICIONAR A COLUNAID DA TABELA QUE VAI FAZER A FOREIGN KEY
);

ALTER TABLE CLIENTE 
ADD CONSTRAINT PK_CLIENTE
PRIMARY KEY(IDCLIENTE)

ALTER TABLE IDTELEFONE 
ADD CONSTRAINT FK_CLIENTE_TELEFONE
FOREIGN KEY(IDCLIENTE)
REFERENCES CLIENTE(IDCLIENTE)

/* DICIONARIO DE DADOS*/

-- USE TABLE_CONSTRAINTS

-- TRAZENDO AS CONSTRAINS DE ALGUM BANCO PROPRIO
SELECT CONTRAINT_SCHEMA AS BANCO,
	   TABLE_NAME AS TABELA,
	   CONTRAINT_NAME AS NOME,
	   CONSTRAINT_TYPE AS TIPO
	   FROM TABLE_CONSTRAINTS
	   WHERE CONSTRAINT_SCHEMA = 'BANCO';
	   
-- APAGANDO CONSTRAINT

ALTER TABLE NomeTabela
DROP FOREIGN KEY NomeConstraint