

/*CAST & CONVERT EM DATA */

-- CONVERT(TIPO_QUE_VAI_SER , VARIAVEL, FORMATO) 105 -- FORMATO - PT-BR

DECLARE 
		@V_NUMERO NUMERIC(10,2) = 100.52,
		@V_DATA DATETIME = GETDATE()
BEGIN
	PRINT 'VALOR NUMERICO: ' + CAST(@V_NUMERO AS VARCHAR)
	PRINT 'VALOR NUMERICO: ' + CONVERT(VARCHAR, @V_NUMERO)
	PRINT 'VALOR DE DATA: ' + CAST(@V_DATA AS VARCHAR)
	PRINT 'VALOR DE DATA: ' + CONVERT(VARCHAR, @V_DATA, 121))
	PRINT 'VALOR DE DATA: ' + CONVERT(VARCHAR, @V_DATA, 120))
	PRINT 'VALOR DE DATA: ' + CONVERT(VARCHAR, @V_DATA, 105)) -- PT-BR
END
GO


