

/* RESULTADOS A VARIAVEIS */

-- TABELA TESTE
CREATE TABLE CARROS(
	CARRO VARCHAR(20),
	FABRICANTE VARCHAR(20)
);
GO

INSERT INTO CARROS VALUES('KA','FORD')
INSERT INTO CARROS VALUES('FIESTA','FORD')
INSERT INTO CARROS VALUES('PRISMA','FORD')
INSERT INTO CARROS VALUES('PALIO','FIAT')
INSERT INTO CARROS VALUES('DOBLO','FIAT')
INSERT INTO CARROS VALUES('UNO','FIAT')
GO

-- DECLARANDO VARIAVEL
DECLATE 
		@V_CONT_FORD INT,
		@v_CONT_FIAT INT
BEGIN
	-- METODO 1 - O SELECT PRECISA RETORNAR UM SIMPLES COLUNA
	-- E UM SÓ RESULTADO
	SET @V_CONT_FORD = (SELECT COUNT(*) FROM CARROS
	WHERE FABRICANTE = 'FORD')
	
	-- MOTODO 2
	SELECT @v_CONT_FIAT = COUNT(*) FROM CARROS 
	WHERE FABRICANTE = 'FIAT'
	
	
END
GO






