

/* ISNULL */

-- VERICICA SE TEM NULO, E SE TIVER FAZ ALGO(A OPERACAO)
-- ESTILO O CASE 

SELECT A.NOME, 
	   ISNULL(T.TIPO," SEM ") AS TIPO, 
	   ISNULL(T.NUMERO, " NUMERO" ) AS TELEFONE, 
	   E.BAIRRO, 
	   E.ESTADO
FROM ALUNO A 
LEFT JOIN TELEFONE T
ON(A.IDALUNO = T.IDALUNO)
INNER JOIN ENDERECO E
ON(A.IDALUNO = E.IDALUNO)
GO

