
/* ALTER TABLE */
--

-- ADICIONADO UMA PK
ALTER TABLE NomeTabela
ADD PRIMARY KEY (Coluna);

-- ADICIONANDO COLUNA SEM POSIÇÃO, ULTIMA POSIÇÃO
ALTER TABLE NomeTabela
ADD Coluna VARCHAR(20);

-- ADICIONANDO COLUNA COM POSIÇÃO
ALTER TABLE NomeTabela
ADD COLUMN Coluna VARCHAR(30) NOT NULL
AFTER ColunaAnteriorQueVaiAdicionar;

-- MODIFICANDO O TIPO DO CAMPO
ALTER TABLE Tabela MODIFY Coluna CHAR(2) NOT NULL;

-- RENOMEANDO TABELA
ALTER TABLE NomeTabela
RENAME NovoNOME

-- FOREIGN KEY
ALTER TABLE NomeTabela
ADD FOREIGN KEY(ColunaID)
REFERENCES Tabela( ColunaID );

