

/* CURSORES */

-- Seria um vetor
-- Usada em tabelas pra fazer operações passando de registro em registro
-- Variaveis são passadas, e sao retornadas
-- Vai pra memoria RAM

-- CRIANDO BANCO
CREATE DATABASE CURSORES.
USE CURSORES;

-- CRIANDO TABELA
CREATE TABLE VENDEDORES(
	ID_VENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50),
	JAN INT,
	FEV INT,
	MARC INT
);

-- INSERINDO VALORES NA TABELA
INSERT INTO VENDEDORES VALUES(NULL,"ALEXANDRE",20,30,50);
INSERT INTO VENDEDORES VALUES(NULL,"RICARDO",50,30,50);
INSERT INTO VENDEDORES VALUES(NULL,"MATHEUS",80,30,50);
INSERT INTO VENDEDORES VALUES(NULL,"ROBSON",20,9.60);

-- QUERY EM LINHA
SELECT NOME, (JAN+FEV+MARC) AS TOTAL FROM VENDEDORES; -- TOTAL
SELECT NOME, (JAN+FEV+MAR)/3 AS MEDIA FROM VENDEDORES; -- MEDIA

-- CRIANDO TABELA, CASO A QUERY É FEITA EM TEMPO REAL EACH
-- ESTA PEGANDO MUITO PROCESASMENTO
CREATE TABLE VEND_TOTAL(
	ID_VENDEDOR INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(50),
	JAN INT,
	FEV INT,
	MARC INT,
	TOTAL INT,
	MEDIA INT
);


DELIMITER $
-- ESTRUTRA PADRAO
CREATE PROCEDURE NOME_PROCEDURE
BEGIN
	-- DECLARAR VARIAVEIS - DECLARE
	DECLARE FIM INT DEFAULT 0;
	
	-- DECLARAR VETOR - TIPO CURSOR
	
	-- VARIAVEL QUE OLHA E VETOR, E QUANDO NAO TEM ELEMENTO PARA O LOOP PRA ESVAZIAR
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;
	
	-- JOGA NA MEMORIA RAM
	OPEN VARIAVEL_CURSOR;
	
	-- LOOP
	REPEAT	
		-- TRAZ O PROXIMO REGISTRO E ARMAZENA AS VARAIAVEIS
		FETCH VARIAVEL_CURSOR INTO VARIAVEIS
		IF NOT FIM THEN
				
			PROGRAMAÇÃO;	
				
		END IF 
		
	UNTIL FIM END REPEAT;
	
	-- LIMPA REGISTRO
	CLOSE VARIAVEL_CURSOR;
END
$

-- CHAMANDO
CALL NOME_PROCEDURE();

-- TESTANDO


-- INSERINDO OS DADOS EM UMA TABELA(VENDEDOR)
-- EM OUTRA TABELA(VEND_TOTAL), POREM IRA TRAZER O TOTAL E A MEDIA
DELIMITER $

CREATE PROCEDURE INSERE_DADOS
BEGIN
	-- DECLARANDO VARIAVEIS - DECLARE
	DECLARE FIM INT DEFAULT 0;
	DECLARE VAR1, VAR2, VAR3, VTOTAL, VMEDIA INT;
	DECLARE VNOME VARCHAR(50);
	
	-- VETOR - CURSOR
	DECLARE REG CURSOR FOR(
		SELECT NOME, JAN, FEV, MARC FROM VENDEDORES;
	);
	
	-- VARIAVEL QUE OLHA E VETOR, E QUANDO NAO TEM ELEMENTO PARA O LOOP PRA ESVAZIAR
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET FIM = 1;
	
	-- JOGA NA MEMORIA RAM
	OPEN REG;
	
	-- LOOP
	REPEAT	
		-- TRAZ O PROXIMO REGISTRO E ARMAZENA AS VARAIAVEIS
		FETCH REG INTO VNOME, VAR1, VAR2, VAR3;
		IF NOT FIM THEN
			-- USASA QUANDO TEM VARIAVEIS
			SET VTOTAL = VAR1 + VAS2 + VAR3;
			SET VMEDIA = VTOTAL / 3;
			
			-- INSERI NA TABELA
			INSERT INTO VEND_TOTAL VALUES(VNOME, VAR1,VAR2,VAR3,VTOTAL,VMEDIA);
		END IF 
		
	UNTIL FIM END REPEAT;
	
	-- LIMPA REGISTRO
	CLOSE REG;
END
$

-- CHAMANDO
CALL INSERE_DADOS();





















