

/* CONSTRAINTS */

-- REGRA COM VALIDAÇÃO
-- CHECK - CHEQUE SE...
ALTER TABLE TABELA
ADD CONSTRAINT NOME_CONSTRAINT CHECK ( SEXO IN(`M`, ` F `));
GO

-- REGRA - FOREIGN KEY
ALTER TABLE TABELA 
ADD CONSTRAINT FK_NOME_CHAVE_ESTRANGEIRA
FOREIGN KEY(COLUNAID)
REFERENCES TABELA(COLUNAID)
GO
