
/* IDENTITY */

-- IGUAL O AUTO_INCREMENT

--(NUMERO_QUE_COMEÇA , INCREMENTADO_DE_TANTOS_POR_TANTOS )

-- PODE COLOCAR OPERAÇÃO, EX IDENTITY(2,2); COMEÇA NO DOIS,E VAI DE DOIS EM DOIS

-- PADRAO É (1,1)

CREATE TABLE TABLE(
	IDTABELA INT PRIMARY KEY IDENTITY;
	NOME VARCHAR(30) NOT NULL,
	SEXO CHAR(1) NOU NULL,
	NASCIMENTO DATE NOT NULL,
	EMAIL VARCHAR(30) UNIQUE
);
GO

-- 1 X 1
-- APLICANDO REGRA
-- IDENTITY(100, 10); COMEÇA NO 100, E VAI DE 10 EM 10
CREATE TABLE TABELA(
	IDTABELA INT PRIMARY KEY IDENTITY(100, 10);
	UF CHAR(2) NOT NULL,
	CHECK (UF IN('RJ', 'SP', 'MG'))
	ID_ESTRANGEIRA INT UNIQUE,
);
GO

