

/* CONVERSOES DA TIPOS DE DADOS */

-- O SINAL DE "+", AGE COMO CONCATENADOR ALEM DE SOMAR

SELECT 1 + '1'
GO -- RETORNA 2

SELECT '1' + '1'
GO -- RETORNA 11

SELECT 'CURSO DE BANCO' + '1'
GO -- RETORNA CURSO DE BANCO1

SELECT 'CURSO DE BANCO' + 1
GO -- ERRO, POIS NAO TEM UM TIPO NUMERICO, E ELE NAO CONVERTE PRA STRING SOZINHO

/* FUNÇÕES DE CONVERSAO DE DADOS */

-- FORCA O CONVERSAO DE UM DADO

-- CAST 
-- CONVERTE EM TODOS ATRIBUTOS

-- STRING EM NUMERICO - VARCHAR PARA INT
SELECT CAST('1' AS INT) + CAST('1' AS INT)
GO -- RETORNA 2

-- NUMERICO EM STRINH - INT PARA VARCHAR
SELECT NOME,
CAST(DAY(NASCIMENTO) AS VARCHAR) + '/' + 
FROM ALUNO
GO

/* CONVERSAO E CONCATENAÇÃO */

SELECT NOME,
CAST(DAY(NASCIMENTO) AS VARCHAR) + '/' + 
CAST(MONTH(NASCIMENTO) AS VARCHAR )+ '/' + 
YEAR(NASCIMENTO) AS VARCHAR) AS NASCIMENTO
FROM ALUNO
GO

