

/* CHARINDEX - RETORNA UM INTEIRO BASEADO NA PROCURA */
-- RETORNA A POSIÇAO DA PROCURA EM INTEIRO SEM O 3° PARAMETRO

-- CHARINDEX(OQUEPROCURA? , ONDEPROCURA?, APARTIRDEQUALPOSIÇÃO ) - RETORNA INTEIRO
/*
	QUANDO PASSA O 3 PARAMETRO, A POSIÇÃO INICIAL QUE ELE CONTA É 1° POSIÇÃO
	POREM ELE NAO CONTA ELA SEN ALGO VALIDO. EXEMPLO:
	
*/

-- QUANDO NAO PASSA O 3° PARAMETRO, A CONTAGEM DEFAULT INICIA EM 1


-- EXEMPLO USANDO O 3° PARAMETRO
SELECT NOME, CHARINDEX('A', NOME, 2) AS INDICE
FROM ALUNOS
GO

O RESULTADO É
-- COMEÇAMOS NA POSIÇÃO 2

aNa 3 - É "3" POIS ELE COMEÇA CONTAR DA POSIÇÃO "1", MAS NAO INCLUI ELA NA PESQUISA
aNDRE 0
rUI 0
jOAO 3 
