

/* CLASULA GO */

-- PACOTES - PCT = CLIENT --->> SERVER

-- QUEBRA AS INSTRUÇÕES EM PACOTES FISICOS, MANTENDO A ORDEM DE EXECUÇÃO
-- QUEBRA OS COMANDOS EM PACOTES FISICOS, MANTENDO A ORDEM DE EXECUÇÃO
-- JEITO MAIS CERTO DE USAR
-- APOS O TERMINO DE CADA QUERY COLOCAR O GO

-- EXEMPLO

CREATE DATABASE NOME_BANCO;
GO

USE NOME_BANCO;
GO

CREATE TABLE TABELA(
	IDTABELA INT
);
GO