
/* SUBCONSULTAS */

SELECT COLUNAS FROM TABELA
WHERE COLUNA = (SUBQUERY);

SELECT COLUNAS FROM TABELA
WHERE COLUNA = (SUBQUERY WHERE COLUNA = (OUTRA SUBQUERIES));

SELECT COLUNAS FROM TABELA
WHERE COLUNA = (SUBQUERY WHERE = (OUTRA SUBQUERIES WHERE COLUNA = (OUTRA SUBQUERIES)));

-- TESTES
SELECT MIN(MARCO) FROM VENDEDORES;

SELECT NOME, MARCO FROM VENDEDORES
WHERE MARCO = (SELECT MIN(MARCO) FROM VENDEDORES);

-- TESTES
SELECT MAX(MARCO) FROM VENDEDORES;

SELECT NOME, MARCO FROM VENDEDORES
WHERE MARCO = (SELECT MAX(MARCO) FROM VENDEDORES);

-- TESTES
SELECT AVG(FEVEREIRO) FROM VENDEDORES;

SELECT NOME, MARCO FROM VENDEDORES
WHERE FEVEREIRO > (SELECT AVG(FEVEREIRO) FROM VENDEDORES);