
/* PROCEDURES */

-- Bloco nomeado, Procedimentos armzenados

DELIMITER $
CREATE PROCEDURE Nome(Parametros)
BEGIN
	QUERYS;
END$

-- Exemplo tabela
CREATE TABLE Curso(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT	
	NOME VARCHAR(30) NOT NULL,
	HORAS INT(3) NOT NULL,
	VALOR FLOAT(10,2) NOT NULL
);

DELIMITER $
CREATE PROCEDURE CadastroCurso(P_NOME VARCHAR(30),P_HORAS INT(3),P_VALOR FLOAT(10,2))
BEGIN
	
	INSERT INTO Curso VALUES(NULL,P_NOME, P_HORAS, P_VALOR);
	
END$

DELIMITER ;
CALL CadastroCurso("MySQL",35, 5000.00);

DELIMITER $
CREATE PROCEDURE ConsultarCurso()
BEGIN
	SELECT * FROM Curso;
END$

DELIMITER ;
CALL ConsultarCurso();
