
/* TRIGGER - GATILHO */

/* AUDITANDO UMA TABELA*/

-- Update

-- Olha a tabela e diz quando foi deletado, 
-- alterado e gravar o valor da alteração

-- Mostra hora atual
SELECT NOW();

-- Mostra o usuario logado e a maquina
SELECT CURRENT_USER();

-- CRIA E USA O BANCO LOJA
CREATE DATABASE LOJA;
USE LOJA

CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	VALOR FLOAT(10,2)
);

INSERT INTO PRODUTO VALUES(NULL,'Tesoura', 100.00);

-- CRIA E USA O BANCO BACKUP
CREATE DATABASE BACKUP;
USE BACKUP

CREATE TABLE BKP_PRODUTO(
	IDBACKUP INT PRIMARY KEY AUTO_INCREMENT,
	IDPRODUTO INT, -- TABLE PRODUTO
	NOME VARCHAR(30),
	VALOR_ORIGINAL FLOAT(10,2),
	VALOR_ALTERADO FLOAT(10,2),
	DATA DATETIME, -- SELECT NOW();
	USUARIO VARCHAR(30), -- SELECT CURRENT_USER();
	EVENTO CHAR(1)
);

-- CRIANDO TRIGGER
-- PEGA O ID DO PRODUTO, NOME E VALOR ANTIGO - OLD
-- E MOSTRA TAMBEM, A DATA QUE FOI FEITO O UPDATE E QUEM FEZ
DELIMITER $
CREATE TRIGGER AUDIT_PROD
AFTER UPDATE ON PRODUTO
FOR EACH ROW
BEGIN

	INSERT INTO BACKUP.BKP_PRODUTO VALUES(NULL, OLD.IDPRODUTO, OLD.NOME, 
	OLD.VALOR, NEW.VALOR, NOW(), CURRENT_USER(), 'U');

END$

-- DANDO UPDATE
UPDATE PRODUTO
SET NOME = ' Martelo '
WHERE NOMEIDPRODUTO = 1;






